/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BachecaRouteImport } from './routes/bacheca'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ImpostazioniRouteImport } from './routes/impostazioni'
import { Route as NoteRouteImport } from './routes/note'
import { Route as VenditeRouteImport } from './routes/vendite'
import { Route as SpazioSpaceIdRouteImport } from './routes/spazio.$spaceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BachecaRoute = BachecaRouteImport.update({
  id: '/bacheca',
  path: '/bacheca',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpostazioniRoute = ImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteRoute = NoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRouteImport,
} as any)
const VenditeRoute = VenditeRouteImport.update({
  id: '/vendite',
  path: '/vendite',
  getParentRoute: () => rootRouteImport,
} as any)
const SpazioSpaceIdRoute = SpazioSpaceIdRouteImport.update({
  id: '/spazio/$spaceId',
  path: '/spazio/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bacheca': typeof BachecaRoute
  '/calendario': typeof CalendarioRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/note': typeof NoteRoute
  '/vendite': typeof VenditeRoute
  '/spazio/$spaceId': typeof SpazioSpaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bacheca': typeof BachecaRoute
  '/calendario': typeof CalendarioRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/note': typeof NoteRoute
  '/vendite': typeof VenditeRoute
  '/spazio/$spaceId': typeof SpazioSpaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bacheca': typeof BachecaRoute
  '/calendario': typeof CalendarioRoute
  '/impostazioni': typeof ImpostazioniRoute
  '/note': typeof NoteRoute
  '/vendite': typeof VenditeRoute
  '/spazio/$spaceId': typeof SpazioSpaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bacheca'
    | '/calendario'
    | '/impostazioni'
    | '/note'
    | '/vendite'
    | '/spazio/$spaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bacheca'
    | '/calendario'
    | '/impostazioni'
    | '/note'
    | '/vendite'
    | '/spazio/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/bacheca'
    | '/calendario'
    | '/impostazioni'
    | '/note'
    | '/vendite'
    | '/spazio/$spaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BachecaRoute: typeof BachecaRoute
  CalendarioRoute: typeof CalendarioRoute
  ImpostazioniRoute: typeof ImpostazioniRoute
  NoteRoute: typeof NoteRoute
  VenditeRoute: typeof VenditeRoute
  SpazioSpaceIdRoute: typeof SpazioSpaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bacheca': {
      id: '/bacheca'
      path: '/bacheca'
      fullPath: '/bacheca'
      preLoaderRoute: typeof BachecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostazioni': {
      id: '/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof ImpostazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendite': {
      id: '/vendite'
      path: '/vendite'
      fullPath: '/vendite'
      preLoaderRoute: typeof VenditeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spazio/$spaceId': {
      id: '/spazio/$spaceId'
      path: '/spazio/$spaceId'
      fullPath: '/spazio/$spaceId'
      preLoaderRoute: typeof SpazioSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BachecaRoute: BachecaRoute,
  CalendarioRoute: CalendarioRoute,
  ImpostazioniRoute: ImpostazioniRoute,
  NoteRoute: NoteRoute,
  VenditeRoute: VenditeRoute,
  SpazioSpaceIdRoute: SpazioSpaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
